/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\knowlegeRefined\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1c792bf6",
    path: "/common/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c792bf6").then(next)
    },
  },
  {
    path: "/common/Git/index.html",
    redirect: "/common/Git/"
  },
  {
    name: "v-9bc56a7c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9bc56a7c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-dfa1a21a",
    path: "/common/React/Advanced.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dfa1a21a").then(next)
    },
  },
  {
    name: "v-95a47936",
    path: "/common/React/REACT%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E7%9A%84%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95a47936").then(next)
    },
  },
  {
    path: "/common/React/REACT开发环境的搭建.html",
    redirect: "/common/React/REACT%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E7%9A%84%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/common/React/REACT开发环境的搭建.html",
    redirect: "/common/React/REACT%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E7%9A%84%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-4abaadb3",
    path: "/common/React/REACT%E7%96%91%E9%97%AE%E6%B1%87%E6%80%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4abaadb3").then(next)
    },
  },
  {
    path: "/common/React/REACT疑问汇总.html",
    redirect: "/common/React/REACT%E7%96%91%E9%97%AE%E6%B1%87%E6%80%BB.html"
  },
  {
    path: "/common/React/REACT疑问汇总.html",
    redirect: "/common/React/REACT%E7%96%91%E9%97%AE%E6%B1%87%E6%80%BB.html"
  },
  {
    name: "v-477cca33",
    path: "/common/React/react.js.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-477cca33").then(next)
    },
  },
  {
    name: "v-c58b4ca6",
    path: "/common/React/Webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c58b4ca6").then(next)
    },
  },
  {
    name: "v-f30c7926",
    path: "/common/TypeScript/READ.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f30c7926").then(next)
    },
  },
  {
    name: "v-49cdbe23",
    path: "/common/React/%E5%88%9D%E8%AF%86REACT.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49cdbe23").then(next)
    },
  },
  {
    path: "/common/React/初识REACT.html",
    redirect: "/common/React/%E5%88%9D%E8%AF%86REACT.html"
  },
  {
    path: "/common/React/初识REACT.html",
    redirect: "/common/React/%E5%88%9D%E8%AF%86REACT.html"
  },
  {
    name: "v-d3e6bff6",
    path: "/common/TypeScript/advanced/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d3e6bff6").then(next)
    },
  },
  {
    path: "/common/TypeScript/advanced/index.html",
    redirect: "/common/TypeScript/advanced/"
  },
  {
    name: "v-1490ec2e",
    path: "/common/React/JSX.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1490ec2e").then(next)
    },
  },
  {
    name: "v-2fade2ac",
    path: "/common/TypeScript/advanced/basic-types.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fade2ac").then(next)
    },
  },
  {
    name: "v-407fdfc8",
    path: "/common/React/%E9%9D%A2%E5%90%91%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-407fdfc8").then(next)
    },
  },
  {
    path: "/common/React/面向组件.html",
    redirect: "/common/React/%E9%9D%A2%E5%90%91%E7%BB%84%E4%BB%B6.html"
  },
  {
    path: "/common/React/面向组件.html",
    redirect: "/common/React/%E9%9D%A2%E5%90%91%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-2d69ad50",
    path: "/common/TypeScript/advanced/declaration-files.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d69ad50").then(next)
    },
  },
  {
    name: "v-0c99609c",
    path: "/common/TypeScript/advanced/declaration-merging.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c99609c").then(next)
    },
  },
  {
    name: "v-a1258eac",
    path: "/common/TypeScript/advanced/symbols.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a1258eac").then(next)
    },
  },
  {
    name: "v-32a12586",
    path: "/common/TypeScript/advanced/iterators-and-generators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32a12586").then(next)
    },
  },
  {
    name: "v-b335ee36",
    path: "/common/TypeScript/basics/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b335ee36").then(next)
    },
  },
  {
    path: "/common/TypeScript/basics/index.html",
    redirect: "/common/TypeScript/basics/"
  },
  {
    name: "v-d8348df4",
    path: "/common/TypeScript/advanced/decorators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8348df4").then(next)
    },
  },
  {
    name: "v-5108c986",
    path: "/common/TypeScript/basics/class-and-interfaces.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5108c986").then(next)
    },
  },
  {
    name: "v-4946a368",
    path: "/common/TypeScript/advanced/variable-declarations.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4946a368").then(next)
    },
  },
  {
    name: "v-1db752b4",
    path: "/common/TypeScript/basics/basic-types.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1db752b4").then(next)
    },
  },
  {
    name: "v-8ab636b4",
    path: "/common/TypeScript/basics/generics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ab636b4").then(next)
    },
  },
  {
    name: "v-6aeafdb8",
    path: "/common/TypeScript/basics/functions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6aeafdb8").then(next)
    },
  },
  {
    name: "v-c31491f4",
    path: "/common/TypeScript/introduction/get-typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c31491f4").then(next)
    },
  },
  {
    name: "v-0423ee8e",
    path: "/common/TypeScript/basics/classes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0423ee8e").then(next)
    },
  },
  {
    name: "v-b0de54b4",
    path: "/common/TypeScript/introduction/what-is-typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b0de54b4").then(next)
    },
  },
  {
    name: "v-b2d4bb62",
    path: "/common/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2d4bb62").then(next)
    },
  },
  {
    path: "/common/index.html",
    redirect: "/common/"
  },
  {
    name: "v-761f2185",
    path: "/deepUse/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-761f2185").then(next)
    },
  },
  {
    path: "/deepUse/index.html",
    redirect: "/deepUse/"
  },
  {
    name: "v-2eb459c5",
    path: "/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2eb459c5").then(next)
    },
  },
  {
    path: "/project/index.html",
    redirect: "/project/"
  },
  {
    name: "v-305050d4",
    path: "/tools/VUEPRESS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-305050d4").then(next)
    },
  },
  {
    name: "v-cab228c8",
    path: "/common/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cab228c8").then(next)
    },
  },
  {
    path: "/common/React/index.html",
    redirect: "/common/React/"
  },
  {
    name: "v-6f502e66",
    path: "/common/TypeScript/basics/interfaces.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f502e66").then(next)
    },
  },
  {
    name: "v-2f829ac6",
    path: "/common/TypeScript/introduction/hello-typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f829ac6").then(next)
    },
  },
  {
    name: "v-2f8ca01c",
    path: "/common/TypeScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f8ca01c").then(next)
    },
  },
  {
    path: "/common/TypeScript/index.html",
    redirect: "/common/TypeScript/"
  },
  {
    name: "v-a6928976",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6928976").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]