/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\knowlegeRefined\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-d3e6bff6",
    path: "/common/TypeScript/advanced/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d3e6bff6").then(next)
    },
  },
  {
    path: "/common/TypeScript/advanced/index.html",
    redirect: "/common/TypeScript/advanced/"
  },
  {
    name: "v-f30c7926",
    path: "/common/TypeScript/READ.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f30c7926").then(next)
    },
  },
  {
    name: "v-9bc56a7c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9bc56a7c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2fade2ac",
    path: "/common/TypeScript/advanced/basic-types.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fade2ac").then(next)
    },
  },
  {
    name: "v-2d69ad50",
    path: "/common/TypeScript/advanced/declaration-files.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d69ad50").then(next)
    },
  },
  {
    name: "v-0c99609c",
    path: "/common/TypeScript/advanced/declaration-merging.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c99609c").then(next)
    },
  },
  {
    name: "v-d8348df4",
    path: "/common/TypeScript/advanced/decorators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8348df4").then(next)
    },
  },
  {
    name: "v-32a12586",
    path: "/common/TypeScript/advanced/iterators-and-generators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32a12586").then(next)
    },
  },
  {
    name: "v-a1258eac",
    path: "/common/TypeScript/advanced/symbols.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a1258eac").then(next)
    },
  },
  {
    name: "v-4946a368",
    path: "/common/TypeScript/advanced/variable-declarations.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4946a368").then(next)
    },
  },
  {
    name: "v-b335ee36",
    path: "/common/TypeScript/basics/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b335ee36").then(next)
    },
  },
  {
    path: "/common/TypeScript/basics/index.html",
    redirect: "/common/TypeScript/basics/"
  },
  {
    name: "v-1db752b4",
    path: "/common/TypeScript/basics/basic-types.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1db752b4").then(next)
    },
  },
  {
    name: "v-5108c986",
    path: "/common/TypeScript/basics/class-and-interfaces.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5108c986").then(next)
    },
  },
  {
    name: "v-0423ee8e",
    path: "/common/TypeScript/basics/classes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0423ee8e").then(next)
    },
  },
  {
    name: "v-6aeafdb8",
    path: "/common/TypeScript/basics/functions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6aeafdb8").then(next)
    },
  },
  {
    name: "v-8ab636b4",
    path: "/common/TypeScript/basics/generics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ab636b4").then(next)
    },
  },
  {
    name: "v-6f502e66",
    path: "/common/TypeScript/basics/interfaces.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f502e66").then(next)
    },
  },
  {
    name: "v-2f8ca01c",
    path: "/common/TypeScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f8ca01c").then(next)
    },
  },
  {
    path: "/common/TypeScript/index.html",
    redirect: "/common/TypeScript/"
  },
  {
    name: "v-c31491f4",
    path: "/common/TypeScript/introduction/get-typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c31491f4").then(next)
    },
  },
  {
    name: "v-2f829ac6",
    path: "/common/TypeScript/introduction/hello-typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f829ac6").then(next)
    },
  },
  {
    name: "v-b0de54b4",
    path: "/common/TypeScript/introduction/what-is-typescript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b0de54b4").then(next)
    },
  },
  {
    name: "v-b2d4bb62",
    path: "/common/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2d4bb62").then(next)
    },
  },
  {
    path: "/common/index.html",
    redirect: "/common/"
  },
  {
    name: "v-761f2185",
    path: "/deepUse/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-761f2185").then(next)
    },
  },
  {
    path: "/deepUse/index.html",
    redirect: "/deepUse/"
  },
  {
    name: "v-2eb459c5",
    path: "/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2eb459c5").then(next)
    },
  },
  {
    path: "/project/index.html",
    redirect: "/project/"
  },
  {
    name: "v-305050d4",
    path: "/tools/VUEPRESS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-305050d4").then(next)
    },
  },
  {
    name: "v-a6928976",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6928976").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]