/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "微光的个人空间",
  "description": "此心光明，夫复何求",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "keywords",
        "content": "前端，博客，微光"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "微光"
      }
    ]
  ],
  "pages": [
    {
      "title": "高级",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/",
      "relativePath": "common/TypeScript/advanced/README.md",
      "key": "v-d3e6bff6",
      "path": "/common/TypeScript/advanced/",
      "headers": [
        {
          "level": 2,
          "title": "基础类型",
          "slug": "基础类型"
        }
      ]
    },
    {
      "title": "前言",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/READ.html",
      "relativePath": "common/TypeScript/READ.md",
      "key": "v-f30c7926",
      "path": "/common/TypeScript/READ.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "前端学习记录",
        "tagline": "微光的个人笔记",
        "actionText": "快速浏览 →",
        "actionLink": "/common/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-9bc56a7c",
      "path": "/"
    },
    {
      "title": "基础类型-高级",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/basic-types.html",
      "relativePath": "common/TypeScript/advanced/basic-types.md",
      "key": "v-2fade2ac",
      "path": "/common/TypeScript/advanced/basic-types.html",
      "headers": [
        {
          "level": 2,
          "title": "类型推断",
          "slug": "类型推断"
        },
        {
          "level": 3,
          "title": "什么是类型推断",
          "slug": "什么是类型推断"
        },
        {
          "level": 2,
          "title": "联合类型",
          "slug": "联合类型"
        },
        {
          "level": 3,
          "title": "简单的例子",
          "slug": "简单的例子"
        },
        {
          "level": 3,
          "title": "访问联合类型的属性或方法",
          "slug": "访问联合类型的属性或方法"
        },
        {
          "level": 3,
          "title": "联合类型赋值的类型推断",
          "slug": "联合类型赋值的类型推断"
        },
        {
          "level": 2,
          "title": "Null 和 Undefined",
          "slug": "null-和-undefined"
        },
        {
          "level": 2,
          "title": "Never",
          "slug": "never"
        }
      ]
    },
    {
      "title": "声明文件",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/declaration-files.html",
      "relativePath": "common/TypeScript/advanced/declaration-files.md",
      "key": "v-2d69ad50",
      "path": "/common/TypeScript/advanced/declaration-files.html",
      "headers": [
        {
          "level": 2,
          "title": "新语法索引",
          "slug": "新语法索引"
        },
        {
          "level": 2,
          "title": "什么是声明语句",
          "slug": "什么是声明语句"
        },
        {
          "level": 2,
          "title": "什么是声明文件",
          "slug": "什么是声明文件"
        },
        {
          "level": 3,
          "title": "第三方声明文件",
          "slug": "第三方声明文件"
        },
        {
          "level": 2,
          "title": "书写声明文件",
          "slug": "书写声明文件"
        },
        {
          "level": 3,
          "title": "全局变量",
          "slug": "全局变量"
        },
        {
          "level": 3,
          "title": "npm 包",
          "slug": "npm-包"
        },
        {
          "level": 3,
          "title": "UMD 库",
          "slug": "umd-库"
        },
        {
          "level": 3,
          "title": "直接扩展全局变量",
          "slug": "直接扩展全局变量"
        },
        {
          "level": 3,
          "title": "在 npm 包或 UMD 库中扩展全局变量",
          "slug": "在-npm-包或-umd-库中扩展全局变量"
        },
        {
          "level": 3,
          "title": "模块插件",
          "slug": "模块插件"
        },
        {
          "level": 3,
          "title": "声明文件中的依赖",
          "slug": "声明文件中的依赖"
        },
        {
          "level": 3,
          "title": "自动生成声明文件",
          "slug": "自动生成声明文件"
        },
        {
          "level": 2,
          "title": "发布声明文件",
          "slug": "发布声明文件"
        },
        {
          "level": 3,
          "title": "将声明文件和源码放在一起",
          "slug": "将声明文件和源码放在一起"
        },
        {
          "level": 3,
          "title": "将声明文件发布到 @types 下",
          "slug": "将声明文件发布到-types-下"
        }
      ]
    },
    {
      "title": "声明合并",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/declaration-merging.html",
      "relativePath": "common/TypeScript/advanced/declaration-merging.md",
      "key": "v-0c99609c",
      "path": "/common/TypeScript/advanced/declaration-merging.html",
      "headers": [
        {
          "level": 2,
          "title": "函数的合并",
          "slug": "函数的合并"
        },
        {
          "level": 2,
          "title": "接口的合并",
          "slug": "接口的合并"
        },
        {
          "level": 2,
          "title": "类的合并",
          "slug": "类的合并"
        }
      ]
    },
    {
      "title": "装饰器",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/decorators.html",
      "relativePath": "common/TypeScript/advanced/decorators.md",
      "key": "v-d8348df4",
      "path": "/common/TypeScript/advanced/decorators.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 3,
          "title": "装饰器的种类",
          "slug": "装饰器的种类"
        },
        {
          "level": 3,
          "title": "类的装饰器",
          "slug": "类的装饰器"
        }
      ]
    },
    {
      "title": "迭代器和生成器",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/iterators-and-generators.html",
      "relativePath": "common/TypeScript/advanced/iterators-and-generators.md",
      "key": "v-32a12586",
      "path": "/common/TypeScript/advanced/iterators-and-generators.html",
      "headers": [
        {
          "level": 2,
          "title": "可迭代性",
          "slug": "可迭代性"
        },
        {
          "level": 3,
          "title": "for..of 语句",
          "slug": "for-of-语句"
        },
        {
          "level": 3,
          "title": "for..of vs. for..in 语句",
          "slug": "for-of-vs-for-in-语句"
        }
      ]
    },
    {
      "title": "Symbols",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/symbols.html",
      "relativePath": "common/TypeScript/advanced/symbols.md",
      "key": "v-a1258eac",
      "path": "/common/TypeScript/advanced/symbols.html"
    },
    {
      "title": "变量声明",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/advanced/variable-declarations.html",
      "relativePath": "common/TypeScript/advanced/variable-declarations.md",
      "key": "v-4946a368",
      "path": "/common/TypeScript/advanced/variable-declarations.html",
      "headers": [
        {
          "level": 2,
          "title": "变量声明",
          "slug": "变量声明-2"
        },
        {
          "level": 2,
          "title": "var 声明",
          "slug": "var-声明"
        },
        {
          "level": 3,
          "title": "作用域规则",
          "slug": "作用域规则"
        },
        {
          "level": 3,
          "title": "捕获变量怪异之处",
          "slug": "捕获变量怪异之处"
        },
        {
          "level": 2,
          "title": "let 声明",
          "slug": "let-声明"
        },
        {
          "level": 3,
          "title": "块作用域",
          "slug": "块作用域"
        },
        {
          "level": 3,
          "title": "重定义及屏蔽",
          "slug": "重定义及屏蔽"
        },
        {
          "level": 3,
          "title": "块级作用域变量的获取",
          "slug": "块级作用域变量的获取"
        },
        {
          "level": 2,
          "title": "const 声明",
          "slug": "const-声明"
        },
        {
          "level": 2,
          "title": "let vs. const",
          "slug": "let-vs-const"
        },
        {
          "level": 2,
          "title": "解构",
          "slug": "解构"
        },
        {
          "level": 3,
          "title": "解构数组",
          "slug": "解构数组"
        },
        {
          "level": 3,
          "title": "对象解构",
          "slug": "对象解构"
        },
        {
          "level": 3,
          "title": "函数声明",
          "slug": "函数声明"
        },
        {
          "level": 3,
          "title": "展开",
          "slug": "展开"
        }
      ]
    },
    {
      "title": "基础",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/basics/",
      "relativePath": "common/TypeScript/basics/README.md",
      "key": "v-b335ee36",
      "path": "/common/TypeScript/basics/"
    },
    {
      "title": "基础类型-入门",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/basics/basic-types.html",
      "relativePath": "common/TypeScript/basics/basic-types.md",
      "key": "v-1db752b4",
      "path": "/common/TypeScript/basics/basic-types.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "布尔值",
          "slug": "布尔值"
        },
        {
          "level": 2,
          "title": "数字",
          "slug": "数字"
        },
        {
          "level": 2,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 2,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 2,
          "title": "元组 Tuple",
          "slug": "元组-tuple"
        },
        {
          "level": 2,
          "title": "枚举",
          "slug": "枚举"
        },
        {
          "level": 2,
          "title": "any",
          "slug": "any"
        },
        {
          "level": 2,
          "title": "void",
          "slug": "void"
        }
      ]
    },
    {
      "title": "类与接口",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/basics/class-and-interfaces.html",
      "relativePath": "common/TypeScript/basics/class-and-interfaces.md",
      "key": "v-5108c986",
      "path": "/common/TypeScript/basics/class-and-interfaces.html",
      "headers": [
        {
          "level": 2,
          "title": "类实现接口",
          "slug": "类实现接口"
        },
        {
          "level": 2,
          "title": "接口继承接口",
          "slug": "接口继承接口"
        },
        {
          "level": 2,
          "title": "接口继承类",
          "slug": "接口继承类"
        },
        {
          "level": 2,
          "title": "混合类型",
          "slug": "混合类型"
        }
      ]
    },
    {
      "title": "类",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/basics/classes.html",
      "relativePath": "common/TypeScript/basics/classes.md",
      "key": "v-0423ee8e",
      "path": "/common/TypeScript/basics/classes.html",
      "headers": [
        {
          "level": 2,
          "title": "类的概念",
          "slug": "类的概念"
        },
        {
          "level": 2,
          "title": "ES6 中类的用法",
          "slug": "es6-中类的用法"
        },
        {
          "level": 3,
          "title": "属性和方法",
          "slug": "属性和方法"
        },
        {
          "level": 3,
          "title": "类的继承",
          "slug": "类的继承"
        },
        {
          "level": 3,
          "title": "存取器",
          "slug": "存取器"
        },
        {
          "level": 3,
          "title": "静态方法",
          "slug": "静态方法"
        },
        {
          "level": 2,
          "title": "ES7 中类的用法",
          "slug": "es7-中类的用法"
        },
        {
          "level": 3,
          "title": "实例属性",
          "slug": "实例属性"
        },
        {
          "level": 3,
          "title": "静态属性",
          "slug": "静态属性"
        },
        {
          "level": 2,
          "title": "TypeScript 中类的用法",
          "slug": "typescript-中类的用法"
        },
        {
          "level": 3,
          "title": "public private 和 protected",
          "slug": "public-private-和-protected"
        },
        {
          "level": 3,
          "title": "readonly",
          "slug": "readonly"
        },
        {
          "level": 3,
          "title": "抽象类",
          "slug": "抽象类"
        },
        {
          "level": 2,
          "title": "类的类型",
          "slug": "类的类型"
        }
      ]
    },
    {
      "title": "函数的类型",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/basics/functions.html",
      "relativePath": "common/TypeScript/basics/functions.md",
      "key": "v-6aeafdb8",
      "path": "/common/TypeScript/basics/functions.html",
      "headers": [
        {
          "level": 2,
          "title": "函数声明",
          "slug": "函数声明"
        },
        {
          "level": 2,
          "title": "函数表达式",
          "slug": "函数表达式"
        },
        {
          "level": 2,
          "title": "用接口定义函数的形状",
          "slug": "用接口定义函数的形状"
        },
        {
          "level": 2,
          "title": "可选参数",
          "slug": "可选参数"
        },
        {
          "level": 2,
          "title": "参数默认值",
          "slug": "参数默认值"
        },
        {
          "level": 2,
          "title": "剩余参数",
          "slug": "剩余参数"
        },
        {
          "level": 2,
          "title": "重载",
          "slug": "重载"
        }
      ]
    },
    {
      "title": "泛型",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/basics/generics.html",
      "relativePath": "common/TypeScript/basics/generics.md",
      "key": "v-8ab636b4",
      "path": "/common/TypeScript/basics/generics.html",
      "headers": [
        {
          "level": 2,
          "title": "简单的例子",
          "slug": "简单的例子"
        },
        {
          "level": 2,
          "title": "多个类型参数",
          "slug": "多个类型参数"
        },
        {
          "level": 2,
          "title": "泛型约束",
          "slug": "泛型约束"
        },
        {
          "level": 2,
          "title": "泛型接口",
          "slug": "泛型接口"
        },
        {
          "level": 2,
          "title": "泛型类",
          "slug": "泛型类"
        }
      ]
    },
    {
      "title": "接口",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/basics/interfaces.html",
      "relativePath": "common/TypeScript/basics/interfaces.md",
      "key": "v-6f502e66",
      "path": "/common/TypeScript/basics/interfaces.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是接口",
          "slug": "什么是接口"
        },
        {
          "level": 2,
          "title": "简单的例子",
          "slug": "简单的例子"
        },
        {
          "level": 2,
          "title": "可选属性",
          "slug": "可选属性"
        },
        {
          "level": 2,
          "title": "任意属性",
          "slug": "任意属性"
        },
        {
          "level": 2,
          "title": "只读属性",
          "slug": "只读属性"
        }
      ]
    },
    {
      "title": "Summary",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "T",
        "8": "S",
        "9": "笔",
        "10": "记",
        "11": "'",
        "12": " ",
        "13": "s",
        "14": "i",
        "15": "d",
        "16": "e",
        "17": "b",
        "18": "a",
        "19": "r",
        "20": ":",
        "21": "a",
        "22": "u",
        "23": "t",
        "24": "o"
      },
      "regularPath": "/common/TypeScript/",
      "relativePath": "common/TypeScript/index.md",
      "key": "v-2f8ca01c",
      "path": "/common/TypeScript/"
    },
    {
      "title": "安装TypeScript",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/introduction/get-typescript.html",
      "relativePath": "common/TypeScript/introduction/get-typescript.md",
      "key": "v-c31491f4",
      "path": "/common/TypeScript/introduction/get-typescript.html",
      "headers": [
        {
          "level": 2,
          "title": "1、在全局环境里安装TS",
          "slug": "_1、在全局环境里安装ts"
        },
        {
          "level": 2,
          "title": "2、用 tsc 命令编译 .ts 文件",
          "slug": "_2、用-tsc-命令编译-ts-文件"
        },
        {
          "level": 2,
          "title": "3、tsconfig.json 配置文件",
          "slug": "_3、tsconfig-json-配置文件"
        }
      ]
    },
    {
      "title": "5分钟了解TypeScript",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/introduction/hello-typescript.html",
      "relativePath": "common/TypeScript/introduction/hello-typescript.md",
      "key": "v-2f829ac6",
      "path": "/common/TypeScript/introduction/hello-typescript.html",
      "headers": [
        {
          "level": 2,
          "title": "构建第一个TypeScript文件",
          "slug": "构建第一个typescript文件"
        },
        {
          "level": 2,
          "title": "类型注解",
          "slug": "类型注解"
        },
        {
          "level": 2,
          "title": "接口",
          "slug": "接口"
        },
        {
          "level": 2,
          "title": "类",
          "slug": "类"
        }
      ]
    },
    {
      "title": "什么是TypeScript",
      "frontmatter": {},
      "regularPath": "/common/TypeScript/introduction/what-is-typescript.html",
      "relativePath": "common/TypeScript/introduction/what-is-typescript.md",
      "key": "v-b0de54b4",
      "path": "/common/TypeScript/introduction/what-is-typescript.html"
    },
    {
      "frontmatter": {
        "0": "s",
        "1": "i",
        "2": "d",
        "3": "e",
        "4": "b",
        "5": "a",
        "6": "r",
        "7": ":",
        "8": "a",
        "9": "t",
        "10": "u",
        "11": "o",
        "12": ";"
      },
      "regularPath": "/common/",
      "relativePath": "common/index.md",
      "key": "v-b2d4bb62",
      "path": "/common/"
    },
    {
      "frontmatter": {},
      "regularPath": "/deepUse/",
      "relativePath": "deepUse/index.md",
      "key": "v-761f2185",
      "path": "/deepUse/"
    },
    {
      "frontmatter": {},
      "regularPath": "/project/",
      "relativePath": "project/index.md",
      "key": "v-2eb459c5",
      "path": "/project/"
    },
    {
      "title": "VUEPRESS",
      "frontmatter": {},
      "regularPath": "/tools/VUEPRESS.html",
      "relativePath": "tools/VUEPRESS.md",
      "key": "v-305050d4",
      "path": "/tools/VUEPRESS.html",
      "headers": [
        {
          "level": 2,
          "title": "1、YARM Front Matter",
          "slug": "_1、yarm-front-matter"
        },
        {
          "level": 2,
          "title": "2、导航栏",
          "slug": "_2、导航栏"
        },
        {
          "level": 2,
          "title": "3、侧边栏",
          "slug": "_3、侧边栏"
        },
        {
          "level": 2,
          "title": "4、SEO",
          "slug": "_4、seo"
        },
        {
          "level": 3,
          "title": "在config里设置head字段",
          "slug": "在config里设置head字段"
        },
        {
          "level": 2,
          "title": "5、更新时间显示",
          "slug": "_5、更新时间显示"
        },
        {
          "level": 2,
          "title": "4、疑问解决",
          "slug": "_4、疑问解决"
        },
        {
          "level": 3,
          "title": "1、vuepress热更新失效问题解决",
          "slug": "_1、vuepress热更新失效问题解决"
        }
      ]
    },
    {
      "title": "vuepress",
      "frontmatter": {},
      "regularPath": "/tools/",
      "relativePath": "tools/index.md",
      "key": "v-a6928976",
      "path": "/tools/",
      "headers": [
        {
          "level": 2,
          "title": "vuepress",
          "slug": "vuepress"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "常见技术栈",
        "link": "/common/"
      },
      {
        "text": "深入理解",
        "link": "/deepUse/"
      },
      {
        "text": "工具和扩展",
        "link": "/tools/"
      },
      {
        "text": "项目",
        "link": "/project/"
      }
    ],
    "sidebar": {
      "/common": [
        "",
        "TypeScript"
      ]
    },
    "lastUpdated": "最后更新时间"
  }
}